#TOTAL_POSTS = 7400200 # Total number of posts on Danbooru
IMG_PER_BATCH = 200 # Read limit from Danbooru
TAGS = ['action', 'looking_at_another', 'romance', 'sad', 'crying', 'angry', 'scared', 'surprised', 'fighting', 'chase', 'talking', 'couple'] # Tags for our categories
#STOP_ID = 7400200
NUM_TAGS = len(TAGS)
## TEMP ##
TOTAL_POSTS = 3727400
JSON_FILE = 'comic_labels.json'
TRAIN_JSON = 'comic_labels_train.json'
VAL_JSON = 'comic_labels_val.json'
GPU_MODE = 0
MPS_MODE = 1
CUDA_DEVICE = 0
NUM_EPOCHS = 5
BASE_LR = 0.001
DECAY_WEIGHT = 0.1 
EPOCH_DECAY = 30 
BATCH_SIZE = 10
IMAGES_DIR = '../comic_images'